/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Avatar: typeof import('primevue/avatar')['default']
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    ConfirmDialog: typeof import('primevue/confirmdialog')['default']
    Dialog: typeof import('primevue/dialog')['default']
    Fieldset: typeof import('primevue/fieldset')['default']
    FloatLabel: typeof import('primevue/floatlabel')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Message: typeof import('primevue/message')['default']
    QuizContent: typeof import('./src/components/QuizContent.vue')['default']
    QuizFooter: typeof import('./src/components/QuizFooter.vue')['default']
    QuizHeader: typeof import('./src/components/QuizHeader.vue')['default']
    QuizIcon: typeof import('./src/components/QuizIcon.vue')['default']
    QuizMain: typeof import('./src/components/QuizMain.vue')['default']
    QuizPagination: typeof import('./src/components/QuizPagination.vue')['default']
    QuizResults: typeof import('./src/components/QuizResults.vue')['default']
    QuizReview: typeof import('./src/components/QuizReview.vue')['default']
    QuizSyntaxHighlighter: typeof import('./src/components/QuizSyntaxHighlighter.vue')['default']
    QuizWelcome: typeof import('./src/components/QuizWelcome.vue')['default']
    RadioButton: typeof import('primevue/radiobutton')['default']
    SelectButton: typeof import('primevue/selectbutton')['default']
    Splitter: typeof import('primevue/splitter')['default']
    SplitterPanel: typeof import('primevue/splitterpanel')['default']
    Tag: typeof import('primevue/tag')['default']
    Toolbar: typeof import('primevue/toolbar')['default']
  }
}
